<a href="https://colab.research.google.com/github/RafiPibe/DecisionTreeML/blob/master/MachineLearning6_5025211074.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install ucimlrepo

In [7]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

import numpy as np
import pandas as pd
import requests
import zipfile
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [8]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
wineQuality = fetch_ucirepo(id=186)

# data (as pandas dataframes)
X = wineQuality.data.features
y = wineQuality.data.targets

# metadata
print(wineQuality.metadata)

# variable information
print(wineQuality.variables)


{'uci_id': 186, 'name': 'Wine Quality', 'repository_url': 'https://archive.ics.uci.edu/dataset/186/wine+quality', 'data_url': 'https://archive.ics.uci.edu/static/public/186/data.csv', 'abstract': 'Two datasets are included, related to red and white vinho verde wine samples, from the north of Portugal. The goal is to model wine quality based on physicochemical tests (see [Cortez et al., 2009], http://www3.dsi.uminho.pt/pcortez/wine/).', 'area': 'Business', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 4898, 'num_features': 11, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['quality'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2009, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C56S3T', 'creators': ['Paulo Cortez', 'A. Cerdeira', 'F. Almeida', 'T. Matos', 'J. Reis'], 'intro_paper': {'title': 'Modeling wine preferences by data mining from physicoc

In [9]:
X.dtypes

fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['fixed_acidity'] = le.fit_transform(X['fixed_acidity'])
X['volatile_acidity'] = le.fit_transform(X['volatile_acidity'])
X['citric_acid'] = le.fit_transform(X['citric_acid'])
X['residual_sugar'] = le.fit_transform(X['residual_sugar'])
X['chlorides'] = le.fit_transform(X['chlorides'])
X['free_sulfur_dioxide'] = le.fit_transform(X['free_sulfur_dioxide'])
X['total_sulfur_dioxide'] = le.fit_transform(X['total_sulfur_dioxide'])
X['density'] = le.fit_transform(X['density'])
X['pH'] = le.fit_transform(X['pH'])
X['sulphates'] = le.fit_transform(X['sulphates'])
X['alcohol'] = le.fit_transform(X['alcohol'])

In [11]:
X.dtypes

fixed_acidity           int64
volatile_acidity        int64
citric_acid             int64
residual_sugar          int64
chlorides               int64
free_sulfur_dioxide     int64
total_sulfur_dioxide    int64
density                 int64
pH                      int64
sulphates               int64
alcohol                 int64
dtype: object

In [12]:
X.head

<bound method NDFrame.head of       fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0                31                36           36             302         34   
1                23                42           34              17         38   
2                43                38           40             101         39   
3                34                28           32             128         47   
4                34                28           32             128         47   
...             ...               ...          ...             ...        ...   
4893             22                24           29              17         28   
4894             27                46           36             120         36   
4895             26                30           19               9         30   
4896             14                40           30               7         11   
4897             19                24           38               2          9  

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit and transform the data
X_normalized = scaler.fit_transform(X)

In [14]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

In [15]:
from sklearn.tree import DecisionTreeClassifier

# Create a DecisionTreeClassifier instance
decision_tree = DecisionTreeClassifier(random_state=42)

# Fit the model to the training data
decision_tree.fit(X_train, y_train)


DecisionTreeClassifier(random_state=42)

In [20]:
# Make predictions on the testing data
y_pred = decision_tree.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix

# Calculate the confusion matrix
confusion = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(confusion)


Confusion Matrix:
[[  0   1   2   2   0   0   0]
 [  1   8   6   7   2   1   0]
 [  0   8 186  81  10   6   0]
 [  1  11  82 273  51  13   1]
 [  0   2   5  57 111  17   0]
 [  0   0   0   9   8  18   0]
 [  0   0   0   0   0   0   0]]


In [22]:
from sklearn.metrics import accuracy_score

# Calculate accuracy on training data
y_train_pred = decision_tree.predict(X_train)
training_accuracy = accuracy_score(y_train, y_train_pred)

# Calculate accuracy on testing data
testing_accuracy = accuracy_score(y_test, y_pred)

print(f"Training Accuracy: {training_accuracy:.2f}")
print(f"Testing Accuracy: {testing_accuracy:.2f}")

Training Accuracy: 1.00
Testing Accuracy: 0.61
